# Generated by Django 5.2.7 on 2025-10-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Comma-separated technologies', max_length=300)),
                ('demo_url', models.URLField(blank=True, help_text='Live demo link')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository link')),
                ('icon', models.CharField(default='🚀', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Lower number = appears first')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
